### PR TITLE
feat(validator): add basic validator

### PR DESCRIPTION
**Pull request by shentschel**
BaseValidator is able to check:
* if an object is initialized
* if an object is not empty
* if an object is an Integer
* if an object is a String
* if an object is an Array

The Validator only throws the first found error.
All errors can be fetched with the
BaseValidator.validateAndFetchErrors() method

Related to: #8

### CODE REVIEW

**Comment by shentschel** [comment]
Lets say... it's a first idea :) Open for discussions!

**Comment by viion** [comment]
This is really good, going to PR and have a nosey and see about adding one for characters.

**Comment by shentschel** [comment]
cool :) How is the progress? Need some help? :D

**Comment by viion** [comment]
Been having a look, got quite busy this week.

How would you `try/catch` an array of errors? I am wondering if it should just fail on the first validation error one rather than keep an array (Like how 404 does).

**Comment by shentschel** [comment]
I think there are 2 possibilities to solve that problem.

The first one would be to create an array of String-Messages instead of an array of exceptions. Then we could use a concanated string in one exception to tell the user all the problems at once.

The second option would be that we add an array to the BaseException class itself, like

```php
public class ValidationException {
  $errors = [];

  public function __construct($message, $code, $throwable, $moreErrors = []) {
    parent::_construct($message, $code, $throwable);
    $this->errors = $moreErrors;
  }
  
  public function getErrors()  {
    return $this->errors;
  } 
}
```

Then we could use something like:

```php
try {
  ... some stuff ...
catch (ValidationException $vex) {
  $allErrors = $vex->getErrors();
  ... do some stuff with the errors ...
}
```

**Comment by viion** [comment]
Done some amends, I don't have any tests for bugged data, quite difficult. Maybe if I feed a modified html form that has purposely broken data.

**Comment by shentschel** [comment]
Hmm a simple test for the validator would do right?

something like (phpunit notation)

```php
namespace \Lodestone\Tests\Validator

use \Phpunit\Framework\TestCase

public class TestValidator extends TestCase {
  public function testStringValidation() {
    // given
   $string = "testString";
   $validator = new BaseValidator($string, "Simple Test String Validation");

   try {
     // when
     $validator
       ->isEmpty()
       ->isString()
       ->validate();  
    } catch (ValidationException $vex) {
      ... failing logic ...
    }
  }

  public function testStringValidationWithNullValue() {
    // given
    $validator = new BaseValidator(null, "Simple Test String Validation");

    try {
      // when
      $validator
        ->isEmpty()
        ->isString()
        ->validate();

        ... failing logic ...
    } catch (ValidationException $vex) {
      // expected
    }
  }
}
```

**Comment by viion** [comment]
Yeah that would work. I want to convert my tests to PHP unit, it's just soooo tedious hah...

We could also add some validation checks against data passed to API.

`searchCharacter > $name` would be a string, should only contains letters and ', not sure how that would work with the existing one as it's quite specific, however `getCharacter > $id` needs to be an `int`, and even though `getCharacterFriends > $id` should also be an int, it will be over 32bit range, so probably have to use `filter_var` vs `is_int` checks.

**Comment by shentschel** [comment]
for the first case you could extend the string test in a specific class like

```php
public class CharacterValidator extends BaseValidator {
	
	private static $NAME_REGEX = '/^[a-zA-Z\']+\s?$/'

	public function __construct($object, $name) {
		parent::_construct($object, $name);
	}

	public function isValidCharacterName() {
		if (!preg_match($object)) {
			... new validation exception ...
		}

		return this;
	}
}
```

then you can do somthing like that in the characters code:

```php
$validator = new CharacterValidator($data->name, 'Character Name');
$validator
  ->isEmpty()
  ->isString()
  ->isValidCharacterName()
  ->validate();
```

**Comment by viion** [comment]
That is really neat, I'm going to merge in this as adding content specific validating would be additional work on top.

**Pull request merged**
