### PR TITLE
Fixed achievements category

### PR DESCRIPTION
**Pull request by Simbiat**
Wrong url binding

### CODE REVIEW

**Comment by viion** [comment]
Ah nice catch, i wonder if we should rename `type` to like `pageId` or something, i know they use `kind` and `category`

**Comment by Simbiat** [comment]
well, in database they use "category" and.... "category" :D https://eu.finalfantasyxiv.com/lodestone/playguide/db/achievement/?category2=1&category3=1

**Comment by viion** [comment]
Haha, `category2/3` i wonder if there is a cat1.

But we're using category already, unless we name `type` to `categoryId` and then the current category could be `subCategory = false`.

Or have a think, it's very minor anyway :)

**Comment by Simbiat** [comment]
category1 is, most likely, linked in the URL after "/db/" (=
I used $type and $category as analogous to Lodestone, but replaced $kind, since $type seems more semantic from coding perspective :D

**Pull request merged**
