### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by Simbiat**
FC formed returns unix timestamp now (which is consistent with other timestamps available so far)
Removed casting to objects in FC model, which broke toArray (sub-arrays were actually objects, even though array-like)
Defaulted $page to 1, since $page always starts from 1, not from "false"
Fixed ranks grabbing in LinkshellMembers
Fixes and updates in some docs

### CODE REVIEW

**Comment by viion** [comment]
Looks good, not keen on the removing cast of (Object), it will eventually go back to an Object once we make a valid entity for it anyway and object is a lot cleaner

`$fc->focus[3]->name` vs `$fc->focus[3]['name']`

toArray should be fine? I see no issues with it?

```
"focus": [
        {
            "status": false,
            "icon": "https:\/\/img.finalfantasyxiv.com\/lds\/h\/9\/2RIcg3Swu7asLE9w5hF11Gm1Sg.png",
            "name": "Role-playing"
        },
        {
            "status": false,
            "icon": "https:\/\/img.finalfantasyxiv.com\/lds\/h\/n\/5Y0D3iH7ngHlRpv9-KJKalt3_o.png",
            "name": "Leveling"
        },
        {
            "status": false,
            "icon": "https:\/\/img.finalfantasyxiv.com\/lds\/h\/t\/Se_50UHNcTNjytzG8olOSGq3MI.png",
            "name": "Casual"
        },
        {
            "status": true,
            "icon": "https:\/\/img.finalfantasyxiv.com\/lds\/h\/i\/1ZVA5nBRhczPW2kJWBJk5Jkz6o.png",
            "name": "Hardcore"
        },
        {
            "status": true,
            "icon": "https:\/\/img.finalfantasyxiv.com\/lds\/h\/7\/jSYmuDYlpVzQ98RA3VhBQWY5PA.png",
            "name": "Dungeons"
        },
        {
            "status": false,
            "icon": "https:\/\/img.finalfantasyxiv.com\/lds\/h\/C\/wiboHfsKd8h_tmbJkNY38w2T8A.png",
            "name": "Guildhests"
        },
        {
            "status": true,
            "icon": "https:\/\/img.finalfantasyxiv.com\/lds\/h\/P\/ydn7ovgdfDc3MocTJV0vP48l4E.png",
            "name": "Trials"
        },
        {
            "status": true,
            "icon": "https:\/\/img.finalfantasyxiv.com\/lds\/h\/R\/R7mn0-cTBIhT8CcxbtDB-YuPUI.png",
            "name": "Raids"
        },
        {
            "status": false,
            "icon": "https:\/\/img.finalfantasyxiv.com\/lds\/h\/D\/hXSGh69WuUbiC5NmlZhDyaO2g8.png",
            "name": "PvP"
        }
    ],
```

**Comment by Simbiat** [comment]
As example of var-dump after toArray with (Object) cast:
`object(stdClass)#503 (2) { ["weekly"]=> string(2) "26" ["monthly"]=> string(2) "11" }`
Perhaps that can/should be amended in toArray function itself, though, dunno.

I am using PHP 7.2 if that matters

**Comment by viion** [comment]
Everything is an object though, these are just casted until entities are created, you would access that as such: `$fc->ranking->weekly` which is better than `$fc->ranking['weekly']`, you change mixes arrays into the object for something that wouldn't be an array anyway, arrays are for lists, not data imo!

**Comment by viion** [comment]
If you're just looking for adjustments to `toArray` then maybe the annotation and that method needs looking into, `toArray` was originally just to allow easier json conversion.

**Comment by Simbiat** [comment]
"better" in this case is very subjective. I need to compare this data to what is already stored in database, which I do retrieve as an array and it's easier to compare array to array, even though in some places I do need to "convert" arrays of arrays to arrays or vice versa.
also, I believe there should be consistency: if toArray is meant to return an array, there should not be any custom objects. Especially, when toArray does not have such issues with characters, which do have arrays of arrays (collectibles) or with member lists for FC and LS.
I can work with objects, but that defeats the purpose of toArray and complicates situations when I want to have full list of members to work with (need to create separate object for each page, from what I gather).

**Comment by viion** [comment]
Add `object` here: https://github.com/viion/lodestone-php/blob/master/src/Lodestone/Entities/AbstractEntity.php#L81

And then fix the annotations in the entities, eg:

```
/**
 * @var object
 */
protected $ranking;
```

And `toArray` will produce: 
```
    [ranking] => Array
        (
            [0] => 121
            [1] => 294
        )
```

You change is changing the entities to arrays when they're not arrays, its entity data and we shouldn't change that logic

**Comment by viion** [comment]
Some of these are just plain wrong :D i never went over them
```
/**
 * @var string
 */
protected $estate;
```

**Comment by Simbiat** [comment]
I noticed that (= Perhaps they just need to be set to actual arrays in there. Or not. Will check on this and commit an update tomorrow morning

**Comment by viion** [comment]
If you revert change `c390cc3` i can fix the entities.

**Comment by Simbiat** [comment]
Well.. something like this... Possibly there is a better way of doing this, though. But just adding "case object" does not work as I'd expect, since we actually have an array of objects in here.

**Comment by viion** [comment]
What outcome do you get? it should work for those that are nested, is the issue specific to those that are an array of data objects?

**Comment by Simbiat** [comment]
issue is with arrays of objects like "focus" for example. I have an idea what may be the cause and will try to make something more proper

**Comment by Simbiat** [comment]
Well, issue here is that those objects are not instanceof AbstractEntity. So it turns into an object of objects and while the outer one is part of AbstractEntity, the rest are not, since you are simply casting them into objects. Since it's object of an object, you need to process outter one first and then everything inside of it, as well. Passing the same through existing "array" logic fails on inner objects, since the cast object does not have toArray method. Let alone, that in "array" way you do not process the "outter" object and thus you lose keys.
I optimized my previous solution a bit, but still, I guess, that proper way would be to make those objects instance of AbstractEntity. At least at the moment I do not see another way. Dunno, if we should really bothered with it now, though.

**Comment by viion** [comment]
Is it possible to do `instanceOf stdClass` ?

**Comment by Simbiat** [comment]
you mean in the for of "object" case? yes, sure, but what for? in this particular case is_object seems equivalent.

**Comment by viion** [comment]
True, your way cleaner

**Comment by Simbiat** [comment]
well, if I'll find a better way - I'll update again, but for now, if you're ok with the change - feel free to merge ;)

**Pull request merged**
