### PR TITLE
Syncing to master

### PR DESCRIPTION
**Pull request by Simbiat**

### CODE REVIEW

**Comment by viion** [comment]
Found an issue?

**Comment by Simbiat** [comment]
Not exactly an issue, but I am updating Achievements a bit. And possibly some other stuff. This one was just for syncing my fork. Will create a pull request a bit later, when I am done.

**Comment by viion** [comment]
Ah okay, something wrong with Achievements? I did do a small fix for some stuff a while ago. Achievements seem to be working for me.

I saw your fix here but it shouldn't be needed since ActiveClass is taken from `mainhand` in the gearset, and in there it contains the same string removal.

**Comment by Simbiat** [comment]
No-no, nothing wrong. More like a new feature :D And, yes, I know, that my old fix is not needed anymore. At least,  should not be (=

**Comment by Simbiat** [comment]
Although, now I am thinking there is a potential way to slightly optimize general character profile as well.

**Comment by viion** [comment]
Sounds awesome :D looking forward to your PR!

**Pull request closed without merging**
