### PR TITLE
Fix for focus/seeking

### PR DESCRIPTION
**Pull request by Simbiat**
If focus is empty (like in 9234490298434916243) focus is populated by "seeking" and "seeking" becomes empty. This is a fix.

### CODE REVIEW

**Comment by viion** [comment]
Any reason to surppress the notice? They're very bad practice

**Comment by Simbiat** [comment]
Cleaner log? From what I understand this can occur,  when there is no materia, but, unclear when exactly: I got notices in cron job, and at the time it was not tracking IDs that caude errors. This does not seem to break anything though.

**Comment by viion** [comment]
What error are you getting? If `$mhtml` is null or badly formatted, maybe we need a check before then. I can't say I've experienced this though (also running a cronjob hitting thousands of characters a minute), is there a particular character we can build a test around?

The rest is good, but I don't really want `@` unless it's out of our scope (eg remote curl)

**Comment by Simbiat** [comment]
It is just a notice. As seen in the comment of the commit. I dunno on which character this happened, but there were like 5 or 6 hits like this in my log overnight. I estimate, that there were no more than 50 thousand character parses. So this is rare.

**Comment by viion** [comment]
I wonder if we should use `array_pad` to enforce a 0?

eg: `list($mname, $mvalue) = array_pad(explode('<br>', html_entity_decode($mhtml)), 2, null);`

This sets `$mname` and `$mvalue` to null unless populated by the `explode`

Seems a bit hacky, I can't check lodestone right now but how does the materia visual look? I forgot what `value` was and if it's needed? Does it show the +XXX amount?

**Comment by Simbiat** [comment]
I can check when I am home

**Comment by viion** [comment]
The other alternative but cleaner approach is to be more specific and ignore materia if we get crap values, eg:

```
$mdata = explode('<br>', html_entity_decode($mhtml));
$mname = $mdata ?? null;
$mvalue = $mvalue ?? null;

if (!$mname || !$mvalue) {
    continue;
}
```

it is a lot more code, however it is very specific and obvious what it does and prevents `$item->addMateria` adding bugged materia.

What you think?

**Comment by Simbiat** [comment]
First value is name of materia and 2nd is its bonus. The notice should appear only if there is no <br> and @ is actually in the wrong place: it should be near $value. But I still was not able to catch it once again.
I added some code on my side to try to catch such notices to get the IDs, but no idea how much we will need to wait.
Removed @ for now. Will update if I catch this again with some more info

**Comment by viion** [comment]
ok, i will merge this as other stuff is great

If you do get a report and find the character, it would be super appreciated, then we could build logic around it. Lodestone is weird sometimes :D

**Pull request merged**
