### PR TITLE
refactor(Parser): implement fail early for wrong http codes

### PR DESCRIPTION
**Pull request by shentschel**
This implements a http code validator. When the remote end returns
something less 200 or bigger than 308 the parsing will fail.

With this we don't need to check the http code on every specific
parsing function. (saves memory and cpu time)

### CODE REVIEW

**Comment by shentschel** [comment]
Well lets say I'm a friend of failing early :) and I thought introducing phpunit bootstrap stuff would ease the transition of #7 :)

**Comment by viion** [comment]
This is good, going to do some PSR fixes.

I wonder if we can get some live tests that go to lodestone.

**Comment by viion** [comment]
Started work on Character validator which can be used as a template. I am going to adjust `BaseValidator`'s `construct()` method optional: `__construct($object = null, $name = null)`

This is so that the same validator can be used without re-creating a new class. This introduces an optional extra method: `->setObject($object, $name)`

Will push soon!

**Comment by shentschel** [comment]
I would prevent live data if possible. when the api and the testsuite is growing it would create a storm of request to lodestone (which will slow down the test environment and also bringing the risk that SE will not be very happy about that.)

But I think it would be very valuable to have live data to test it. So my proposal would be to create a local snapshot of valid data and create html snippets with it. That would save time because we don't have to fetch the sites everytime we start the testsuite.

also sorry for the 2 spaces stuff and the user info x) I need to reconfigure my intellij to stop that.

**Comment by viion** [comment]
A local snapshot could work however it would kind of invalidate it as it would always pass once the test created. When SE update lodestone, it would still pass but in production it would fail, and this is why I would like live testing.

I don't think there is an issue with the requests. Tests are only run by yourself, when you want to check everything is working. Even if tests are run on a live service the interval can be set to daily.

Considering I hit Lodestone with 2million requests a day and that don't include everyone else, there is usually not a problem with request spam so long as it's consistent and constrained.

**Comment by viion** [comment]
For some bizzare reason I am getting `is_int` failures:

```
Object = 730968

failed is_int
```

Code:
```
$validator = new CharacterValidator();
$validator->setObject($this->data['id'], 'ID')->isInteger();
```

(`setObject` mimics what `__construct` does.

Will look after lunch XD

**Comment by shentschel** [comment]
Hmm, then how about we split up the testsuite into 2 testsuites. One for unittesting every operation in iteself and one which does integration tests (e.g. doing a end-to-end test which fetches live data and then checks in the end that the result is as expected)

**Comment by viion** [comment]
We can split it up, right now running `php tests/run.php` will do all live testing and that is partially automated and is a solution right now. However doesn't exactly run on services

**Comment by shentschel** [comment]
Well lets move the CI services question for a date when we moved all tests to phpunit and implemented the missing tests x) I think I will spend the weekend on refactoring all the existing tests to phpunit :)

**Comment by viion** [comment]
Started character validation, will add more later but I think it sets up a good template to follow and more specifics can be added to `CharacterValidator`.

```
$validator
    ->set($this->data['id'], 'ID')->isNumeric()
    ->set($this->data['name'], 'Name')->isValidCharacerName()
    ->set($this->data['server'], 'Server')->isString()
    ->set($this->data['title'], 'Title')->isString(true);
```

I wonder if we should have a URL validation method, eg; Checking images are from the `finalfantasyxiv` domain, and validating forum links for dev posts.

**Comment by shentschel** [comment]
hmm I'm against checking URLs. The reason is, that there are so many caveeats when it comes to URLs... e.g. a chinese url can contain unicode symbols... and you have to fix the url regex everytime square decides to change their URL pattern. In the end it is a question of how often will there be links from SE which have the wrong domain x) so when it happens quite often we can implement it.

My 2 cents :D

**Comment by shentschel** [comment]
I will create issues for the stuff we discussed here :) So we can keep track of them even when this PR is closed x)

**Comment by shentschel** [comment]
Good morning :)

I fixed some hiccups and renamed set to checkIf.
A reason for that is that is much easier to understand (A good book for that topic: http://ricardogeek.com/docs/clean_code.html)

**Comment by viion** [comment]
I wonder if `checkIf` can just be `check`, not a fan of 2 letter camelCase.

Any reason to remove object from report? Makes it very difficult to debug when it just says "Name is not valid", but I don't know why without having to go output it on its own.

**Comment by shentschel** [comment]
We can rename it, yes :) It was only for unterstanding and even check is more understandable than set.

I removed Object from the report because an empty object would produce lines like 'ID () is not set'.
Another example is the type validation. When you add an array as object. the string format throws an exception because it cannot convert the array into a string x)

**Comment by viion** [comment]
Can convert to json if array. Then it's visible.

**Comment by shentschel** [comment]
that would do too :) Feel free to revert the change. :)

**Comment by viion** [comment]
Just pushed, changed `checkIf`to `check` (I'm so picky sorry!)

I've updated all tests and ensured they pass with the changes to allow `$object` to be printed for debugging, it's only part of `type` checks and not empty ones.

I've also added `isStringOrEmpty`, this is because while: `$string = ''` would pass in `isString()`, $string = null` would not, and it's more likely to end up being `null` than an empty string, especially as some parts of the parser preset `$this->add('grand_company', null)`.

Need to add similar one for arrays, `isArrayOrEmpty`. 

*(Could be renamed to `isArrayOrNull` and `isStringOrNull`) probably...*

**Comment by shentschel** [comment]
hmm I think isString/ArrayOrEmpty is ok for now :)  As long as it is consistant with all other names (PHP is a bad example for naming functions consistantly)

**Comment by shentschel** [comment]
BTW: I think we should merge that PR :) We implemented more features than the title expresses.

**Pull request merged**
