### PR TITLE
Avoid empty data

### PR DESCRIPTION
**Pull request by Simbiat**
Added up to 5 tries in case $data is empty to counter occasional empty pages being processed. If nothing is grabbed and it was not 404 - return regular false, since we can't determine what is the actual cause.

### CODE REVIEW

**Comment by viion** [comment]
Nice, little worried about the while loop and any possible memory leaks, I'm thinking if it fails or returns empty it might down to the developer to handle it in their code rather than in he API

This also is similar to the need for data validation which would prevent it parsing or providing empty data

**Comment by Simbiat** [comment]
well, validation should be done as soon as we get data in several hops, IMHO, and it should not throw and unhandled exception, rather handle it somehow. Since we now know when an issue can occur and that a simple retry should solve this... Hence the loop. Since issue is rare, it will break on 1st iteration most of the time, so I would not worry about possible leaks, besides there are only 5 tries. Now, how to handle "false" or "404" is still up to the person using the API. For example, I will be ignoring "false" completely, but if I am updating an entity and get 404 I will mark it as deleted.

**Comment by Simbiat** [comment]
I thought about it a bit more... The purpose of this was to solve a fatal error, rather than ensure we have data, so I removed the loop. Technically this could have been done inside ensureHTML, but I believe, that it's more logical to validate data when we actually try to grab it, rather then on next step

**Comment by viion** [comment]
It might be good to make this into a setting with the ability to set custom retry, I'll do some edits to your PR tomorrow.

I would like to add options to many parts so it would be good to start now and help track this

**Comment by Simbiat** [comment]
Options in the call or as a configuration?

**Comment by viion** [comment]
Yes a configuration, eg:

```php
$api->setConfig([
    'retry' => true,
    'retry_attempts' => 5,
]);
```

etc. I have some ideas for customizing things like base lodestone url, language, and if to ignore xivdb or not.

**Comment by shentschel** [comment]
Hmm I think I would throw an exception when there is an empty webpage and the error code is 2XX (which defines that there was no error nor a redirect). That would allow the user to react to an error while parsing the data. 

My 2 cents :)

**Comment by viion** [comment]
Could do, then the developer just needs to `try/catch`, which would also work if parsing several characters at once.

**Comment by shentschel** [comment]
yeah and it saves cpu cycles because we don't need logic to react on such errors which also wouldn't decrease the performance of the api (Fetching the data from lodestone takes a fair amount of time even without parsing it)

**Comment by Simbiat** [comment]
yeah, you tell me... Updating all members with Server information for http://simbiat.ru/fftracker/ took around 46 hours in TEN threads. Insanity (=

**Comment by viion** [comment]
Get a Japan server for $5/mo and do 300k in half a day!

**Comment by Simbiat** [comment]
nah... only if people will actually be using the service, which is unlikely (=

**Comment by viion** [comment]
Going to close this as there are conflicts and it should be solved now real validation is in place.

Something like this:

```php
try {
    $character = $api->getCharacter('xxx');
} catch (ValidationException $vex) {
    echo "Error: ". $vex->getMessage();
}
```

**Pull request closed without merging**
