### PR TITLE
Hope(profile): hope that this increases parsing a profile

### PR DESCRIPTION
**Pull request by shentschel**
Related to: #21

### CODE REVIEW

**Comment by shentschel** [comment]
Continuation of PR#24...

I was not able to append that to the original PR x) and I was to lazy(sleepy) to merge that stuff right now

**Comment by viion** [comment]
I'm going to do some tweaks, it's improving though. Removing just `id` was the biggest factor I think, a drop of `0.001`

Here are my results:

---

# Previous PR: 

- `php tests/cli.php character`
Avg: 0.103 - 0.109

**Average Line Costs**
```
10 entries for: Lodestone\Parser\Character -> parse | Average time: 1196.6 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfile | Average time: 45.4 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileId | Average time: 8.4 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileName | Average time: 2.4 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileServer | Average time: 2 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileTitle | Average time: 2.1 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfilePicture | Average time: 3.2 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileBiography | Average time: 16.6 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileDetails | Average time: 23.1 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileNameDay | Average time: 23.6 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileGuardian | Average time: 3.8 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileCity | Average time: 13.7 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileGrandcompany | Average time: 13 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileFreeCompany | Average time: 3.6 microseconds
10 entries for: Lodestone\Parser\Character -> parseClassJobs | Average time: 22.9 microseconds
10 entries for: Lodestone\Parser\Character -> parseAttributes | Average time: 119.1 microseconds
10 entries for: Lodestone\Parser\Character -> parseCollectables | Average time: 208.7 microseconds
10 entries for: Lodestone\Parser\Character -> parseEquipGear | Average time: 32.4 microseconds
10 entries for: Lodestone\Parser\Character -> parseActiveClass | Average time: 129.5 microseconds
```

# This PR


- `php tests/cli.php character`
Avg: 0.102 - 0.109

**Average Line Costs**
```
10 entries for: Lodestone\Parser\Character -> parse | Average time: 1267.3 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfile | Average time: 41.5 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileName | Average time: 7.9 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileServer | Average time: 1.8 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileTitle | Average time: 1.9 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfilePicture | Average time: 3 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileBiography | Average time: 15.6 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileDetails | Average time: 24.1 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileNameDay | Average time: 23 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileGuardian | Average time: 3.3 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileCity | Average time: 10.8 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileGrandcompany | Average time: 11.3 microseconds
10 entries for: Lodestone\Parser\Character -> parseProfileFreeCompany | Average time: 3.2 microseconds
10 entries for: Lodestone\Parser\Character -> parseClassJobs | Average time: 20.1 microseconds
10 entries for: Lodestone\Parser\Character -> parseAttributes | Average time: 112.8 microseconds
10 entries for: Lodestone\Parser\Character -> parseCollectables | Average time: 178.2 microseconds
10 entries for: Lodestone\Parser\Character -> parseEquipGear | Average time: 34.4 microseconds
10 entries for: Lodestone\Parser\Character -> parseActiveClass | Average time: 127.7 microseconds
```

**Comment by viion** [comment]
I wonder if `AbstractEntity` could be removed, which just sets `BaseValidator`, this validator would always get overwritten, I think all entities should have their own validator to keep it consistent and ready.

**Comment by shentschel** [comment]
hmm we can do this. Then we would save one inherit layer

**Comment by viion** [comment]
Actually we will leave it for now, having a validator for city, guardian, etc would be quite tedious since they would all be blank files extending BaseValidator.

**Comment by shentschel** [comment]
well that blank files (only with setters and getters) is a main principle in MVC Architectures x)

**Comment by viion** [comment]
Getting weird bugs in this PR

```
PHP Notice:  Indirect modification of overloaded property Lodestone\Dom\Element::$outertext has no effect in /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Parser/Character.php on line 174
PHP Stack trace:
PHP   1. {main}() /Users/joshfreeman/Web/Misc/lodestone-php/tests/cli.php:0
PHP   2. Lodestone\Api->getCharacter() /Users/joshfreeman/Web/Misc/lodestone-php/tests/cli.php:31
PHP   3. Lodestone\Parser\Character->parse() /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Api.php:112
PHP   4. Lodestone\Parser\Character->parseClassJobs() /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Parser/Character.php:60
```

**Comment by shentschel** [comment]
hmm maybe it is one of the by value to by reference changes I did x)

**Comment by viion** [comment]
I might take what you have and from master go from there applying these changes, while tidying some stuff up.

**Comment by shentschel** [comment]
gimme a sec x) I found the bug

**Comment by shentschel** [comment]
Now the bug is gone

**Comment by viion** [comment]
Okay, it's consistently lower at the moment, going to do some tweaks. I think reference variables *may* be slower.

- `php tests/cli.php character`
Avg: 0.100 - 0.104

**Comment by shentschel** [comment]
hmm I think it depends on the case. When you modify the variable a reference can be faster because he does not copy the value (e.g. on big arrays). Maybe I should read a little more about that reference stuff x)

**Comment by shentschel** [comment]
found another line where it was useless x) 

The only thing that is interesting is, that I had improved parsing times yesterday in the evening with that changes 🤔

**Comment by viion** [comment]
I'm changing benchmark to be snippet based rather than timing entire runs as it's hard to keep consistent.

**Comment by viion** [comment]
Here we go, much simplier and cleaner benchmark:

```

 -----------------
 BENCHMARK RESULTS
 -----------------

 Completed in: 	 6.12067 ms
 Memory Usage: 	 4 mb
 CPU Usage: 	 1.97021
 Records: 	 12

 !! Lodestone\Parser\Character::parse    Line: 55 to 62
 !! 5 entries   average: 0.08461137 ms   low: 0.07761502 - high: 0.095227

 !! Lodestone\Parser\CharacterProfileTrait::parseProfileName    Line: 65 to 67
 !! 5 entries   average: 0.00116887 ms   low: 0.0001688 - high: 0.00512815

    Lodestone\Parser\CharacterProfileTrait::parseProfileServer    Line: 77 to 79
    5 entries   average: 0.00016947 ms   low: 9.894E-5 - high: 0.00034714

    Lodestone\Parser\CharacterProfileTrait::parseProfileTitle    Line: 89 to 93
    5 entries   average: 0.00016661 ms   low: 0.00010586 - high: 0.00029993

    Lodestone\Parser\CharacterProfileTrait::parseProfilePicture    Line: 103 to 108
    5 entries   average: 0.000315 ms   low: 0.00019813 - high: 0.00062108

 !! Lodestone\Parser\CharacterProfileTrait::parseProfileBiography    Line: 116 to 122
 !! 5 entries   average: 0.0015008 ms   low: 0.00137615 - high: 0.00167799

 !! Lodestone\Parser\CharacterProfileTrait::parseProfileDetails    Line: 132 to 145
 !! 5 entries   average: 0.00206776 ms   low: 0.00186706 - high: 0.00241804

    Lodestone\Parser\CharacterProfileTrait::parseProfileNameDay    Line: 155 to 159
    5 entries   average: 0.00022635 ms   low: 0.00015783 - high: 0.00036788

    Lodestone\Parser\CharacterProfileTrait::parseProfileGuardian    Line: 169 to 177
    5 entries   average: 0.00026164 ms   low: 0.0002389 - high: 0.00029302

 !! Lodestone\Parser\CharacterProfileTrait::parseProfileCity    Line: 185 to 194
 !! 5 entries   average: 0.00100422 ms   low: 0.00092006 - high: 0.00117803

    Lodestone\Parser\CharacterProfileTrait::parseProfileGrandcompany    Line: 204 to 216
    5 entries   average: 0.00022535 ms   low: 0.0002079 - high: 0.00025201

    Lodestone\Parser\CharacterProfileTrait::parseProfileFreeCompany    Line: 226 to 230
    5 entries   average: 0.00028672 ms   low: 0.00016594 - high: 0.00061202
```

It is handled via:

```php
Benchmark::start(__METHOD__,__LINE__);
// some code
Benchmark::finish(__METHOD__,__LINE__);
```

It times a snippet of code within a function, so only include it before/after function. I tried to do magic methods `__call()` to automate this but it wasn't working, so ditched it.

This also improves the dev debug times:

```
Duration: 6.04062400   + 1.55077600  !     Line 55    in  Lodestone\Parser\Character::parse
Duration: 6.04185000   + 0.00122600        Line 65    in  Lodestone\Parser\CharacterProfileTrait::parseProfileName
Duration: 6.04204300   + 0.00019300        Line 67    in  Lodestone\Parser\CharacterProfileTrait::parseProfileName
```

It properly displays class/trait.

I've also made the cli have some options:

- `php tests/bench.php 5`

Will run 5 tests, or put it to 100 for 100 parses

- `php tests/bench.php 5 y`

Will show the full unprocessed report array, rather than a cleaner human report.

**Comment by shentschel** [comment]
hmm seems that sys_getloadavg() does not work on windows with xampp x)

```
 -----------------
 BENCHMARK RESULTS
 -----------------

 Completed in:   5.90735 ms
 Memory Usage:   4 mb
PHP Fatal error:  Uncaught Error: Call to undefined function sys_getloadavg() in D:\dev\projects\lodestone-php\src\Lodestone\Modules\Benchmark.php:188
Stack trace:
#0 D:\dev\projects\lodestone-php\src\Lodestone\Modules\Benchmark.php(135): Lodestone\Modules\Benchmark::cpu()
#1 D:\dev\projects\lodestone-php\tests\bench.php(33): Lodestone\Modules\Benchmark::report(false)
#2 {main}
  thrown in D:\dev\projects\lodestone-php\src\Lodestone\Modules\Benchmark.php on line 188

Fatal error: Uncaught Error: Call to undefined function sys_getloadavg() in D:\dev\projects\lodestone-php\src\Lodestone\Modules\Benchmark.php:188
Stack trace:
#0 D:\dev\projects\lodestone-php\src\Lodestone\Modules\Benchmark.php(135): Lodestone\Modules\Benchmark::cpu()
#1 D:\dev\projects\lodestone-php\tests\bench.php(33): Lodestone\Modules\Benchmark::report(false)
#2 {main}
  thrown in D:\dev\projects\lodestone-php\src\Lodestone\Modules\Benchmark.php on line 188
```

**Comment by viion** [comment]
Ew Windows? :P Could remove it as it's not that important, or use the supplied vagrant.

**Comment by shentschel** [comment]
Yeah... gaming with linux or mac is not that easy xD

The benchmarking seems strange in a way... 

```php
Benchmark::start(__METHOD__.'_VALIDATE',__LINE__);
/*
$this->validator
    ->check($server, 'Server')
    ->isInitialized()
    ->isNotEmpty()
    ->isString()
    ->validate();
*/
Benchmark::finish(__METHOD__.'_VALIDATE',__LINE__);
```

As you can see, I commented out the validation of the server name.
The result after that for exactly this line was:

```
 !! Lodestone\Entities\Character\Profile::setServer_VALIDATE    Line: 179 to 186
 !! 10 entries   average: 0.003069 ms   low: 0.00044084 - high: 0.01550412
```

So no execution seems to take some time :o

**Comment by viion** [comment]
Yeah it will, that is natural and the benchmark does some stuff it itself which can be costly. Thats why I added the constant as in production this would be removed.

However, the point is to determine if something increases.

If benchmark takes 300 ms and your code 5 ms, you'd get 305, if you do a change and you get 307, your code is now 7s. etc

Don't need to know too much about the exact timing, just if it goes up or down on average.

**Comment by viion** [comment]
It is very easy to get very tiny values, eg:

```
    Lodestone\Parser\Character::parse    Line: 55 to 64
    5 entries   average: 3.061E-5 ms   low: 2.193E-5 - high: 5.984E-5
```

I may set everything below a specific amount to 0, eg: `0.00001 = 0`.

**Comment by viion** [comment]
Interesting, so I looked at the function `bcsub` which does float subtraction a lot better and gets around the float-E issue.

Here is a report:

```
 Completed in: 	 1.51071 ms
 Memory Usage: 	 4 mb
 Records: 	 12

 !! Lodestone\Parser\Character::parse    Line: 55 to 64
 !! 2 entries   average: 0.09925 ms   low: 0.07960 - high: 0.11890

 !! Lodestone\Parser\CharacterProfileTrait::parseProfileName    Line: 65 to 67
 !! 2 entries   average: 0.00775 ms   low: 0.00020 - high: 0.01530

    Lodestone\Parser\CharacterProfileTrait::parseProfileServer    Line: 77 to 79
    2 entries   average: 0.00030 ms   low: 0.00020 - high: 0.00040

    Lodestone\Parser\CharacterProfileTrait::parseProfileTitle    Line: 89 to 93
    2 entries   average: 0.00025 ms   low: 0.00010 - high: 0.00040

    Lodestone\Parser\CharacterProfileTrait::parseProfilePicture    Line: 103 to 108
    2 entries   average: 0.00035 ms   low: 0.00010 - high: 0.00060

 !! Lodestone\Parser\CharacterProfileTrait::parseProfileBiography    Line: 116 to 122
 !! 2 entries   average: 0.00150 ms   low: 0.00140 - high: 0.00160

 !! Lodestone\Parser\CharacterProfileTrait::parseProfileDetails    Line: 132 to 145
 !! 2 entries   average: 0.00275 ms   low: 0.00190 - high: 0.00360

    Lodestone\Parser\CharacterProfileTrait::parseProfileNameDay    Line: 155 to 159
    2 entries   average: 0.00025 ms   low: 0.00010 - high: 0.00040

    Lodestone\Parser\CharacterProfileTrait::parseProfileGuardian    Line: 169 to 177
    2 entries   average: 0.00040 ms   low: 0.00030 - high: 0.00050

    Lodestone\Parser\CharacterProfileTrait::parseProfileCity    Line: 185 to 194
    2 entries   average: 0.00100 ms   low: 0.00100 - high: 0.00100

    Lodestone\Parser\CharacterProfileTrait::parseProfileGrandcompany    Line: 204 to 216
    2 entries   average: 0.00025 ms   low: 0.00020 - high: 0.00030

    Lodestone\Parser\CharacterProfileTrait::parseProfileFreeCompany    Line: 226 to 230
    2 entries   average: 0.00040 ms   low: 0.00020 - high: 0.00060
```

Also, with no coding at all:

```
 Completed in: 	 1.3274 ms
 Memory Usage: 	 4 mb
 Records: 	 1

    Lodestone\Parser\Character::parse    Line: 55 to 64
    2 entries   average: 0.00000 ms   low: 0.00000 - high: 0.00000
```

0 ms :) as you'd expect, you sometimes get 0.00001 or 0.00005 because there was a tick during excution.

**Comment by shentschel** [comment]
that sounds better :) My problem was that even the benchmark does not need the same time every time. so I was hard to see if the change in time came from my code or from the benchmark x)

I'll check it now. But I think I did all I know to reduce the needed time as much as possible

**Comment by viion** [comment]
Okay name is fine, there is an initial like "boot up" that is slow, so whatever parse is first will come back slow. But then it's fast after, assuming as it's opcached.

**Comment by viion** [comment]
Running a bench on 100 characters now, looking at it its average round `0.079` to `0.085` which is fantastic really, this is for concurrent runs, the initial run is always the slowest as it has IO overhead, second + is mostly read from opcache (especially loading things like the XIVDB data into arrays)

I've implemented a `toArray()` which will bundle up all params with `@var <type>` if the type is not a basic one it assumes it's a class and calls `toArray()` on that (effectively recursion across classes)

```
 -----------------
 BENCHMARK RESULTS
 -----------------

 Completed in: 	 146.7087 ms
 Memory Usage: 	 2,439 kb
 Records: 	 19

 !! [100] Lodestone\Parser\Character::parse   line: 56 to 63
 !! average: 0.08379 ms     low: 0.07660 - high: 0.10590     Mem: 2,025 kb - 3,029 kb

    [100] Lodestone\Parser\CharacterProfileTrait::parseProfileName   line: 61 to 63
    average: 0.00018 ms     low: 0.00010 - high: 0.00540     Mem: 2,026 kb - 2,952 kb

    [100] Lodestone\Parser\CharacterProfileTrait::parseProfileServer   line: 73 to 75
    average: 0.00010 ms     low: 0.00000 - high: 0.00030     Mem: 2,506 kb - 2,952 kb

    [100] Lodestone\Parser\CharacterProfileTrait::parseProfileTitle   line: 85 to 89
    average: 0.00007 ms     low: 0.00000 - high: 0.00030     Mem: 2,507 kb - 2,952 kb

    [100] Lodestone\Parser\CharacterProfileTrait::parseProfilePicture   line: 99 to 104
    average: 0.00017 ms     low: 0.00010 - high: 0.00050     Mem: 2,509 kb - 2,953 kb

    [100] Lodestone\Parser\CharacterProfileTrait::parseProfileBiography   line: 112 to 118
    average: 0.00147 ms     low: 0.00120 - high: 0.00220     Mem: 2,510 kb - 2,953 kb

 !! [100] Lodestone\Parser\CharacterProfileTrait::parseProfileRaceClanGender   line: 128 to 141
 !! average: 0.00208 ms     low: 0.00170 - high: 0.00420     Mem: 2,512 kb - 2,953 kb

    [100] Lodestone\Parser\CharacterProfileTrait::parseProfileNameDay   line: 151 to 155
    average: 0.00013 ms     low: 0.00010 - high: 0.00040     Mem: 2,514 kb - 2,953 kb

    [100] Lodestone\Parser\CharacterProfileTrait::parseProfileGuardian   line: 165 to 173
    average: 0.00024 ms     low: 0.00020 - high: 0.00070     Mem: 2,515 kb - 2,953 kb

    [100] Lodestone\Parser\CharacterProfileTrait::parseProfileCity   line: 181 to 190
    average: 0.00099 ms     low: 0.00080 - high: 0.00220     Mem: 2,517 kb - 2,954 kb

    [100] Lodestone\Parser\CharacterProfileTrait::parseProfileGrandcompany   line: 200 to 212
    average: 0.00022 ms     low: 0.00010 - high: 0.00060     Mem: 2,519 kb - 2,954 kb

    [100] Lodestone\Parser\CharacterProfileTrait::parseProfileFreeCompany   line: 222 to 226
    average: 0.00018 ms     low: 0.00010 - high: 0.00050     Mem: 2,520 kb - 2,954 kb

 !! [100] Lodestone\Parser\Character::parseClassJobs   line: 77 to 120
 !! average: 0.01043 ms     low: 0.00870 - high: 0.01620     Mem: 2,522 kb - 2,974 kb

 !! [100] Lodestone\Parser\Character::parseAttributes   line: 192 to 302
 !! average: 0.01040 ms     low: 0.00860 - high: 0.01650     Mem: 2,544 kb - 2,990 kb

 !! [100] Lodestone\Parser\Character::parseCollectables   line: 310 to 338
 !! average: 0.01873 ms     low: 0.01590 - high: 0.02850     Mem: 2,563 kb - 3,026 kb

    [0] Lodestone\Parser\Character::fetchCollectable   line: 348 to
    average: 0.00000 ms     low: 0.00000 - high: 0.00000     Mem: 2,605 kb -

 !! [100] Lodestone\Parser\Character::parseEquipGear   line: 367 to 460
 !! average: 0.01833 ms     low: 0.01640 - high: 0.02350     Mem: 2,655 kb - 3,030 kb

 !! [100] Lodestone\Parser\Character::parseActiveClass   line: 130 to 184
 !! average: 0.01175 ms     low: 0.01030 - high: 0.01600     Mem: 2,663 kb - 3,029 kb

    [400] Lodestone\Entities\AbstractEntity::toArray   line: 44 to 81
    average: 0.00005 ms     low: 0.00000 - high: 0.00020     Mem: 2,667 kb - 3,041 kb
```

**Comment by viion** [comment]
Current data

```
Array
(
    [hash] => 323bd1de43009f13dcdc93822e50d5bee348848c
    [id] => 730968
    [name] => Premium Virtue
    [server] => Phoenix
    [title] =>
    [avatar] => http://img2.finalfantasyxiv.com/f/73cbde3df508fa147006c64859727aae_5047bc596a4bab2dc7f7c120bb22dec5fc0_96x96.jpg
    [portrait] => http://img2.finalfantasyxiv.com/f/73cbde3df508fa147006c64859727aae_5047bc596a4bab2dc7f7c120bb22dec5fl0_640x873.jpg
    [biography] => 4f77e6744e
    [race] => Hyur
    [clan] => Midlander
    [gender] => female
    [nameday] => 2nd Sun of the 6th Umbral Moon
    [guardian] => Array
        (
            [id] => 9
            [name] => Azeyma, the Warden
            [icon] => http://img.finalfantasyxiv.com/lds/h/2/a0fvYSx_56BEzhPPYyLykkdZ6k.png
        )

    [city] => Array
        (
            [id] => 1
            [name] => Limsa Lominsa
            [icon] => http://img.finalfantasyxiv.com/lds/h/j/Xlz3DzGOKmwiDGho5aGWaudRNI.png
        )

    [grandcompany] => Array
        (
            [id] => 3
            [name] => Immortal Flames
            [icon] => http://img.finalfantasyxiv.com/lds/h/K/RCtWRMlTFAQh67FRG-QGXryviw.png
            [rank] => Second Flame Lieutenant
        )

    [freecompany] => 9231253336202687179
)
```

**Comment by viion** [comment]
Done all my tweaks in terms of performance or getting it to work. I think it could do with some drastic cleaning up, moving things to trait or shuffling things around. Just so it is explicity what is parsing, and what is Not.

I might move the folder in `Parser` up a structure like this:

```
Lodestone
 | Parser
 | -- Character
 | -- -- Profile
 | -- -- Collectables
 | -- -- Gear
 | -- FreeCompany
```

etc

**Comment by shentschel** [comment]
looks pretty nice :D The only thing - which is terrifying - is the reflection stuff (https://stackoverflow.com/questions/294582/php-5-reflection-api-performance).

But I can't provide a better alternative for a generic toArray function

**Comment by viion** [comment]
In PHP7 it is much faster, you could just rely on `get_class_vars`, or we could manually create `toArray` methods which would be the fastest. I didn't see any dramatic performance issues, however I need to test it with and without it at a good scale.

**Comment by shentschel** [comment]
Would be cool to know the numbers from the test :D

**Comment by shentschel** [comment]
Maybe we should merge it soon so that we can start to merge all api-calls into the new structure :)

**Pull request merged**
