### PR TITLE
Allow dash in names

### PR DESCRIPTION
**Pull request by Simbiat**
Dashes are valid in names. I am also pretty sure, I saw some other characters in names, but can be wrong on that account.

Also, not sure I like validator throwing fatal errors everywhere. Interrupts my bulk updates on http://simbiat.ru/fftracker =(

### CODE REVIEW

**Comment by shentschel** [comment]
there would be a way to make an error non fatal. IMHO I think we should stick with the fatal one because invalid data is mostly a sign of a processing error or a data inconsistency. In both cases there could be unpredictable behavior if something goes wrong. In the end you can try-catch the errors and implement some logic or you can help us improving the filters like you did with this PR :)

So thanks for the contribution :D 👍

**Comment by viion** [comment]
I will make a new character and see what it lets me do.

Got the errors, put try/catch around the chunk of your code (doesnt need to be specific bits it can be the entire of it) and this let's you track errors if you wanted!

**Comment by Simbiat** [comment]
I tried try/catch and it still failed. I have code like this
```php
$parser = new Lodestone\Parser\FreeCompany();
try {
$fcdatatmp = $parser->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_FREECOMPANY_URL, $id))->parse();
catch (Exception $e) {
echo 'error: ',  $e->getMessage(), "\n";
}
```
but it still went to fatal error tracing to the line in "try". Specifically, I was trying to catch error in case of 404, sending $id as "1".

And of course I will be contributing. I am not as high-level and I am more used to procedural style, but if I find something, I will share it. After all I have a whole service that depends on this parser 😃

**Comment by viion** [comment]
I think it throws `ValidationException`,

My test code:
```php
try {
    $data = $api->getCharacter($id ? $id : 730968, $hash);
} catch (\Lodestone\Validator\ValidationException $ex) {
    echo 'error';
}
```

We could add an option to silence exceptions if it becomes problematic for basic usage.

**Comment by shentschel** [comment]
Well I don't know it is only a typo but your try catch block is missing a closing }.

I marked it with underscores in the example below :)

```php
$parser = new Lodestone\Parser\FreeCompany();
try {
  $fcdatatmp = $parser->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_FREECOMPANY_URL, $id))->parse();
_}_ catch (Exception $e) {
  echo 'error: ',  $e->getMessage(), "\n";
}
```

**Comment by shentschel** [comment]
character creation screen says that you can only use letters, hypens and apostrophes

**Comment by Simbiat** [comment]
Practice shows, that dashes are allowed - http://eu.finalfantasyxiv.com/lodestone/character/?q=-&worldname=Cerberus&classjob=&race_tribe=&blog_lang=ja&blog_lang=en&blog_lang=de&blog_lang=fr&order=

As for my catch, issue was the bad namespace. Did not think about that. So now I am able to catch errors representing 404, which is good, but I tried to replace the page with a non-Lodestone one to see how it will be handled and... it went to Fatal Error with TypeError now:
```
PHP Warning:  dom_import_simplexml() expects parameter 1 to be object, boolean given in \\backend\\Lodestone\\Dom\\Document.php on line 94
PHP Notice:  Trying to get property of non-object in \\backend\\Lodestone\\Dom\\Document.php on line 94
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to DOMXPath::__construct() must be an instance of DOMDocument, null given in \\backend\\Lodestone\\Dom\\Document.php:156\nStack trace:\n#0 \\backend\\Lodestone\\Dom\\Document.php(156): DOMXPath->__construct(NULL)\n#1 \\backend\\Lodestone\\Parser\\ParserHelper.php(95): Lodestone\\Dom\\Document->find('.ldst__window ....', 0)\n#2 \\backend\\Lodestone\\Parser\\FreeCompany.php(38): Lodestone\\Parser\\ParserHelper->getDocumentFromClassname('.ldst__window ....', 0)\n#3 \\backend\\Lodestone\\Parser\\FreeCompany.php(25): Lodestone\\Parser\\FreeCompany->parseHeader()\n#4 in \\backend\\Lodestone\\Dom\\Document.php on line 156
```
I do understand, that it's a different type of exception, but perhaps this one should be tracked by Validator, too? Like validate .ldst__window is present?

**Comment by viion** [comment]
Think this talk is: http://www.dashhyphen.com/

:D

**Comment by shentschel** [comment]
We aren't finished with adding the validator to all parts right now x) So I think we will also have a look into that :D

**Pull request merged**
